---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    target:
      auth:
        server: "https://api.ocp4demo.sc.osecloud.com:6443"
        token: "WmndH2U7QB39WcxH8WmhdS71DR5dmjlKHr9ND-ZgwJE"
    serviceMesh:
      namespace: istio-system

  tasks:
    - name: Authenticating with target cluster using {{ target.auth.server }}.
      command: oc login --token={{ target.auth.token }} --server={{ target.auth.server }}
    - name: Querying services with label {{ service.selector }}
      command: oc get ServiceMeshMemberRoll default --namespace {{ serviceMesh.namespace }} -o jsonpath='{.spec.members}'
      register: services
      # loop: "{{ services.stdout_lines }}"
    - debug: var={{ services.stdout }}
